# This is the main workflow for the CI/CD pipeline.
# It is triggered on push to main, develop, or feature/* branches,
# and on pull requests to main or develop branches.
# It also has a manual trigger for workflow_dispatch.
name: CI/CD

on:
  push:
    branches: [ main, develop, feature/* ]
    paths:
      - 'templates/**'
      - '**.py'
      - 'requirements.txt'
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env:
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}

      # Test steps can be added here if needed

  deploy-production:
    needs: test-and-build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Deploy to Render
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        env:
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}

  deploy-staging:
    needs: test-and-build
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
      - name: Deploy to Render (Staging)
        run: curl ${{ secrets.RENDER_STAGING_DEPLOY_HOOK_URL }}
        env:
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
